name: planner_app
description: Plan your plans :)
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  auto_route: ^8.0.3
  auto_route_generator: ^8.0.0
  get_it: ^7.6.4
  freezed_annotation: ^2.4.1
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  isar: ^3.0.0-dev.8
  isar_flutter_libs: ^3.1.0+1
  flutter_svg: ^2.0.9
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  path_provider: ^2.1.2
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  isar_generator: ^3.1.0+1
  flutter_lints: ^3.0.1
  freezed: ^2.4.5
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  assets:
    - assets/icons/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
  generate: true
  uses-material-design: true

